### ISSUE TITLE
Callers and Callees of a given or all methods 

### ISSUE THREAD

**Issue by razuiit** [INRIA/spoon#1832]
Dear all I am new in spoon and want to access the callers and callees of a given or all the methods (one by one) from project
Any clue?

**Comment by surli** [comment]
Hi @razuiit 

you might use custom filters based on the methods you want to get the callees/callers. First you have to collect all the methods of your project. 

You can do it for example with this kind of code:
```java
Launcher spoonLauncher = new Launcher();
// process your source code with the right arguments 
CtModel model = spoonLauncher.getModel();

List<CtMethod<?>> allMethods = model.getElements(new TypeFilter<>(CtMethod.class));
```

Then you can iterate on all methods to get the invocations of those methods:
```java
for (CtMethod<?> myMethod : allMethods) {
   CtExecutableReference execRef = myMethod.getReference();
   List<CtInvocation> invocations = model.getElements(new InvocationFilter(execRef));

  // you can iterate on invocations and use invocation.getTarget() to get the caller  
}
```

**Comment by razuiit** [comment]
Hi Surli, Thanks for your response. I tried the code you sent to me and it helps after casting.
However, I am getting this error: 
Exception in thread "main" spoon.support.SpoonClassNotFoundException: cannot load class: org.apache.tools.ant.Task

I guess this is because of my following statement in model building:
spoon.getEnvironment().setNoClasspath(true);

But removing this statement prompt a different error. 
Exception in thread "main" spoon.compiler.ModelBuildingException: The import org.apache.commons.logging cannot be resolved at D:\Implementations\Experiments\muCommander0.8.5\mucommander-0.8.5\mucommander-0.8.5\source\com\mucommander\file\impl\s3\S3ProtocolProvider.java:26
 Here is my code:
public class MethodRetrieval  {
    public CtModel createModel()
    {
        Launcher spoon = new Launcher();
        spoon.addInputResource("D:\\Implementations\\Experiments\\muCommander0.8.5\\mucommander-0.8.5\\mucommander-0.8.5");
        spoon.getEnvironment().setNoClasspath(true);
        spoon.buildModel();
        return spoon.getModel();

    }
    public static void main(String[] args) {
         MethodRetrieval retrieval= new MethodRetrieval();
        CtModel model=retrieval.createModel();
        List<CtMethod> allMethods = model.getElements(new TypeFilter<>(CtMethod.class));
        for (CtMethod<?> myMethod : allMethods) {
   CtExecutableReference execRef = myMethod.getReference();
   List<CtInvocation<?>> invocations = model.getElements(new InvocationFilter(execRef));
        }
     }

}

**Comment by surli** [comment]
@razuiit no actually you need the statement:
`spoon.getEnvironment().setNoClasspath(true);` if you do not give to Spoon the whole classpath of the code you want to analyze. 

Can you try your code with Spoon 6.2.0-SNAPSHOT? It looks like a bug we already fixed.
If it does not work can you paste the complete stack trace of the error you get? Thanks.

**Comment by razuiit** [comment]
I am still getting error:
Here is the stack trace:
Exception in thread "main" spoon.support.SpoonClassNotFoundException: cannot load class: org.apache.tools.ant.Task
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:164)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getActualClass(CtTypeReferenceImpl.java:146)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.getTypeDeclaration(CtTypeReferenceImpl.java:190)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.getExecutableDeclaration(CtExecutableReferenceImpl.java:169)
	at spoon.support.reflect.reference.CtExecutableReferenceImpl.isOverriding(CtExecutableReferenceImpl.java:259)
	at spoon.reflect.visitor.filter.InvocationFilter.matches(InvocationFilter.java:54)
	at spoon.reflect.visitor.filter.InvocationFilter.matches(InvocationFilter.java:28)
	at spoon.reflect.visitor.chain.CtQueryImpl$3.apply(CtQueryImpl.java:185)
	at spoon.reflect.visitor.chain.CtQueryImpl$3.apply(CtQueryImpl.java:182)
	at spoon.reflect.visitor.chain.CtQueryImpl$FunctionWrapper._accept(CtQueryImpl.java:526)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:319)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:88)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtBlock(CtScanner.java:298)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:48)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.CtScanner.visitCtConstructor(CtScanner.java:366)
	at spoon.support.reflect.declaration.CtConstructorImpl.accept(CtConstructorImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtClass(CtScanner.java:334)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:68)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:647)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:646)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:646)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:646)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:89)
	at spoon.reflect.visitor.CtScanner.visitCtPackage(CtScanner.java:646)
	at spoon.support.reflect.declaration.CtPackageImpl.accept(CtPackageImpl.java:57)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.CtScanner.scan(CtScanner.java:164)
	at spoon.reflect.visitor.CtScanner.visitCtModule(CtScanner.java:922)
	at spoon.reflect.factory.ModuleFactory$CtUnnamedModule.accept(ModuleFactory.java:105)
	at spoon.reflect.visitor.filter.CtScannerFunction$Scanner.doScan(CtScannerFunction.java:91)
	at spoon.reflect.visitor.EarlyTerminatingScanner.scan(EarlyTerminatingScanner.java:104)
	at spoon.reflect.visitor.filter.CtScannerFunction.apply(CtScannerFunction.java:65)
	at spoon.reflect.visitor.filter.CtScannerFunction.apply(CtScannerFunction.java:35)
	at spoon.reflect.visitor.chain.CtQueryImpl$LazyFunctionWrapper._accept(CtQueryImpl.java:505)
	at spoon.reflect.visitor.chain.CtQueryImpl$AbstractStep.accept(CtQueryImpl.java:319)
	at spoon.reflect.visitor.chain.CtQueryImpl.forEach(CtQueryImpl.java:105)
	at spoon.reflect.visitor.chain.CtQueryImpl.list(CtQueryImpl.java:118)
	at spoon.reflect.visitor.chain.CtQueryImpl.list(CtQueryImpl.java:112)
	at spoon.reflect.CtModelImpl.getElements(CtModelImpl.java:138)
	at networkcoupling.MethodRetrieval.main(MethodRetrieval.java:43)
Caused by: java.lang.ClassNotFoundException: org.apache.tools.ant.Task
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at spoon.support.reflect.reference.CtTypeReferenceImpl.findClass(CtTypeReferenceImpl.java:162)
	... 73 more
Java Result: 1

**Comment by razuiit** [comment]
Hi Surli, Here is the latest update:
I try to run your snapshot code, it work well until it get the following line of code:
List<CtInvocation<?>> invocations = model.getElements(new InvocationFilter(execRef));
Following error thrown:
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project NetworkDependencies: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Below is my pom file, Am i making some thing wrong in pom? I might need to add my processor "MethodRetrieval". However, I am not sure where in the pom I can add that...

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>NetworkDependencies</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
   
<dependencies>
	<dependency>
		<groupId>fr.inria.gforge.spoon</groupId>
		<artifactId>spoon-core</artifactId>
		<version>6.2.0-SNAPSHOT</version>
	</dependency>
</dependencies>
<repositories>
	<repository>
		<id>gforge.inria.fr-snapshot</id>
		<name>Maven Repository for Spoon Snapshot</name>
		<url>http://spoon.gforge.inria.fr/repositories/snapshots/</url>
		<snapshots />
	</repository>
</repositories>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>
</project>

**Comment by surli** [comment]
Apparently we indeed have a bug in Spoon with the InvocationFilter I suggested you to use. 
You should be able to create your own custom filter with a code like that:

```java
public class CustomInvocationFilter implements Filter<CtInvocation<?>> {

	private CtExecutableReference<?> executable;

	public CustomInvocationFilter(CtExecutableReference<?> executable) {
		this.executable = executable;
	}

	@Override
	public boolean matches(CtInvocation<?> invocation) {
		return invocation.getExecutable().equals(executable);
	}
}
```

> I might need to add my processor "MethodRetrieval". However, I am not sure where in the pom I can add that...

Not sure to understand your problem here: you have several ways to use Spoon. Here it seems that you use it as an API: by adding Spoon-core to your project, you can use directly the API, then if your processor is present as a class of your project it's available, you only have to reference it to the launcher using `Launcher#addProcessor`.

**Comment by monperrus** [comment]
closing this inactive thread. don't hesitate to reopen.

**Comment by masud-technope** [comment]
This simple code does not work with ```spoon-core-7.5.0-beta-20-jar-with-dependencies.jar```
```
CtClass<?> l = Launcher
                .parseClass("public class A { void m() { System.out.println(\"yeah\");} }");
		System.out.println(l.getQualifiedName());
```
The above code is showing this error:
```
Exception in thread "main" java.lang.NoSuchFieldError: MODULE_INFO_FILE_NAME
	at spoon.support.compiler.jdt.JDTBatchCompiler.getCompilationUnits(JDTBatchCompiler.java:78)
	at spoon.support.compiler.jdt.JDTBatchCompiler.getUnits(JDTBatchCompiler.java:255)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnits(JDTBasedSpoonCompiler.java:402)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildUnitsAndModel(JDTBasedSpoonCompiler.java:361)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.buildSources(JDTBasedSpoonCompiler.java:329)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:112)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:95)
	at spoon.Launcher.buildModel(Launcher.java:761)
	at spoon.Launcher.parseClass(Launcher.java:860)
	at spoon.practices.SpoonStarter.main(SpoonStarter.java:16)
```
Any help will be appreciated.
